### ISSUE TITLE
Turing Fallo al abrir SAP en Producción Valorem

### ISSUE THREAD

**Issue by carlosgiraldo** [FridaSupport/TuringSuport#121]
Buenos días pueden ayudarme a revisar por que Turing no pudo ingresar al SAP GUI?

El Turing intento tantas veces en ejecutar el SAP GUI que Windows decidió cerrarlo. 

Yo cerré el Turing y lo volví a abrir y realizo las ejecución de forma correcta ingresando a SAP.

![SEGUNDO_00](https://user-images.githubusercontent.com/14879161/58181762-fed48500-7c71-11e9-8779-1555fc9f0eb6.png)

![SEGUNDO_01](https://user-images.githubusercontent.com/14879161/58182369-17916a80-7c73-11e9-98e2-545e542bbbe9.png)

![SEGUNDO_02](https://user-images.githubusercontent.com/14879161/58181915-46f3a780-7c72-11e9-9a6c-26d45256e14a.png)

El log:

5/14/2019 7:17:40 PM - Execution started
5/14/2019 7:17:40 PM - If Result : True
5/14/2019 7:17:40 PM - If Block Running
5/14/2019 7:17:40 PM - #SAP RunSapInstance "06-BW-QAS Valorem" 500 "YYYYYYYYYY" "XXXXXXXXX" ES graphics: Running
5/14/2019 7:17:40 PM - SAP RunSapInstance "06-BW-QAS Valorem" 500 "YYYYYYYYYY" "XXXXXXXXX" ES graphics : Success
5/14/2019 7:17:40 PM - SAP RunSapInstance "05-BW-PRD Valorem" 500 "YYYYYYYYYY" "XXXXXXXXX" ES graphics: Running
5/14/2019 7:17:42 PM - error: RunSapInstance "05-BW-PRD Valorem" 500 "YYYYYYYYYY" "XXXXXXXXX" ES graphics : System.Runtime.InteropServices.COMException (0x0000026B): The control could not be found by id.
   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at SAPFEWSELib.ISapSessionTarget.FindById(String Id, Object Raise)
   at SapScriptReader.SapScriptExecute.CLickButtonById(String ButtonId) in C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 872
   at SapScriptReader.SapScriptExecute.login(String action) in C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 758
5/14/2019 7:17:42 PM - SAP RunSapInstance "05-BW-PRD Valorem" 500 "YYYYYYYYYY" "XXXXXXXXX" ES graphics : Error
5/14/2019 7:17:42 PM - SAP StartTransaction rspcm: Running
5/14/2019 7:17:43 PM - SAP StartTransaction rspcm : Success
5/14/2019 7:17:43 PM - SAP ClickGridToolBtn GridId wnd[0]/usr/cntlALV/shellcont/shell ButtonId "&MB_FILTER": Running
5/14/2019 7:17:43 PM - error: ClickGridToolBtn GridId wnd[0]/usr/cntlALV/shellcont/shell ButtonId "&MB_FILTER" : System.Runtime.InteropServices.COMException (0x0000026B): The control could not be found by id.
   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at SAPFEWSELib.ISapSessionTarget.FindById(String Id, Object Raise)
   at SapScriptReader.SapScriptExecute.ClickGridToolButton(String GridId, String ButtonId) in C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 3062
   at SapScriptReader.SapScriptExecute.ClickGridToolBtn(String action) in C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 2823
5/14/2019 7:17:43 PM - SAP ClickGridToolBtn GridId wnd[0]/usr/cntlALV/shellcont/shell ButtonId "&MB_FILTER" : Error
5/14/2019 7:17:43 PM - error: selectm id "wnd[0]/mbar/menu[4]/menu[12]" : System.Runtime.InteropServices.COMException (0x0000026B): The control could not be found by id.
   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at SAPFEWSELib.ISapSessionTarget.FindById(String Id, Object Raise)
   at SapScriptReader.SapScriptExecute.SelectMenuById(String MenuId) in C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 1650
   at SapScriptReader.SapScriptExecute.SelectMenu(String action) in C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 1628
5/14/2019 7:17:43 PM - error: click id "wnd[1]/usr/btnSPOP-OPTION1" : System.Runtime.InteropServices.COMException (0x0000026B): The control could not be found by id.
   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at SAPFEWSELib.ISapSessionTarget.FindById(String Id, Object Raise)
   at SapScriptReader.SapScriptExecute.CLickButtonById(String ButtonId) in C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 872
   at SapScriptReader.SapScriptExecute.CLickButton(String action) in C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 848
5/14/2019 7:17:43 PM - Execution ended

gracia, quedo atento.

**Comment by gantonioid** [comment]
@eradgg ya lo viste?

**Comment by carlosgiraldo** [comment]
Realizando pruebas creo que el problema es que se queda una sesión de SAP en el limbo computacional y al tratar de ingresar al SAP Logon nuevamente se presenta el error que impide ingresar a SAP, yo estoy realizando un kill a saplogon y por ahora esta solucionando mi problema, de todas formas quedo atento a la respuesta que me puedan dar y a una posible solución, gracias.

**Comment by eradgg** [comment]
Hola Carlos.

Podemos tener una llamada para revisaro?

saludos.

**Comment by eradgg** [comment]
Tenemos un work Around matando la tarea de SAP para poder continuar, pero necesitamos darle seguimiento para por medio de Frida identificar cuando estén corriendo más de 1 sesión de SAP.
